package com.sunyard.core.S010010086;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-01-04T14:08:27.805+08:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://esb.spdbbiz.com/services/S010010086/wsdl", name = "ESBServerPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ESBServerPortType {

    @WebMethod(operationName = "LcyFcyDmdSvgCashTlly", action = "urn:/LcyFcyDmdSvgCashTlly")
    @WebResult(name = "RspLcyFcyDmdSvgCashTlly", targetNamespace = "http://esb.spdbbiz.com/services/S010010086", partName = "RspLcyFcyDmdSvgCashTlly")
    public RspLcyFcyDmdSvgCashTllyType lcyFcyDmdSvgCashTlly(
            @WebParam(partName = "ReqLcyFcyDmdSvgCashTlly", name = "ReqLcyFcyDmdSvgCashTlly", targetNamespace = "http://esb.spdbbiz.com/services/S010010086")
                    ReqLcyFcyDmdSvgCashTllyType reqLcyFcyDmdSvgCashTlly
    );
}
