package com.sunyard.core.S120020064;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-01-04T14:14:10.573+08:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://esb.spdbbiz.com/services/S120020064/wsdl", name = "ESBServerPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ESBServerPortType {

    @WebMethod(operationName = "UnifyUsrAuthn", action = "urn:/UnifyUsrAuthn")
    @WebResult(name = "RspUnifyUsrAuthn", targetNamespace = "http://esb.spdbbiz.com/services/S120020064", partName = "RspUnifyUsrAuthn")
    public RspUnifyUsrAuthnType unifyUsrAuthn(
            @WebParam(partName = "ReqUnifyUsrAuthn", name = "ReqUnifyUsrAuthn", targetNamespace = "http://esb.spdbbiz.com/services/S120020064")
                    ReqUnifyUsrAuthnType reqUnifyUsrAuthn
    );
}
