package com.sunyard.core.S120050006;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-01-04T14:14:45.989+08:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://esb.spdbbiz.com/services/S120050006/wsdl", name = "ESBServerPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ESBServerPortType {

    @WebMethod(operationName = "RcnclFlDwld", action = "urn:/RcnclFlDwld")
    @WebResult(name = "RspRcnclFlDwld", targetNamespace = "http://esb.spdbbiz.com/services/S120050006", partName = "RspRcnclFlDwld")
    public RspRcnclFlDwldType rcnclFlDwld(
            @WebParam(partName = "ReqRcnclFlDwld", name = "ReqRcnclFlDwld", targetNamespace = "http://esb.spdbbiz.com/services/S120050006")
                    ReqRcnclFlDwldType reqRcnclFlDwld
    );

    @WebMethod(operationName = "UnvslDtlRcnclDwld", action = "urn:/UnvslDtlRcnclDwld")
    @WebResult(name = "RspUnvslDtlRcnclDwld", targetNamespace = "http://esb.spdbbiz.com/services/S120050006", partName = "RspUnvslDtlRcnclDwld")
    public RspUnvslDtlRcnclDwldType unvslDtlRcnclDwld(
            @WebParam(partName = "ReqUnvslDtlRcnclDwld", name = "ReqUnvslDtlRcnclDwld", targetNamespace = "http://esb.spdbbiz.com/services/S120050006")
                    ReqUnvslDtlRcnclDwldType reqUnvslDtlRcnclDwld
    );

    @WebMethod(operationName = "StmtQryAndPrt", action = "urn:/StmtQryAndPrt")
    @WebResult(name = "RspStmtQryAndPrt", targetNamespace = "http://esb.spdbbiz.com/services/S120050006", partName = "RspStmtQryAndPrt")
    public RspStmtQryAndPrtType stmtQryAndPrt(
            @WebParam(partName = "ReqStmtQryAndPrt", name = "ReqStmtQryAndPrt", targetNamespace = "http://esb.spdbbiz.com/services/S120050006")
                    ReqStmtQryAndPrtType reqStmtQryAndPrt
    );
}
