package com.sunyard.core.S090030081;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-01-04T14:13:41.609+08:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://esb.spdbbiz.com/services/S090030081/wsdl", name = "ESBServerPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ESBServerPortType {

    @WebMethod(operationName = "FncPosFlQry", action = "urn:/FncPosFlQry")
    @WebResult(name = "RspFncPosFlQry", targetNamespace = "http://esb.spdbbiz.com/services/S090030081", partName = "RspFncPosFlQry")
    public RspFncPosFlQryType fncPosFlQry(
            @WebParam(partName = "ReqFncPosFlQry", name = "ReqFncPosFlQry", targetNamespace = "http://esb.spdbbiz.com/services/S090030081")
                    ReqFncPosFlQryType reqFncPosFlQry
    );
}
