package com.sunyard.core.S070030011;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-01-04T14:13:29.155+08:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://esb.spdbbiz.com/services/S070030011/wsdl", name = "ESBServerPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ESBServerPortType {

    @WebMethod(operationName = "OthrSysExgCodeQry", action = "urn:/OthrSysExgCodeQry")
    @WebResult(name = "RspOthrSysExgCodeQry", targetNamespace = "http://esb.spdbbiz.com/services/S070030011", partName = "RspOthrSysExgCodeQry")
    public RspOthrSysExgCodeQryType othrSysExgCodeQry(
            @WebParam(partName = "ReqOthrSysExgCodeQry", name = "ReqOthrSysExgCodeQry", targetNamespace = "http://esb.spdbbiz.com/services/S070030011")
                    ReqOthrSysExgCodeQryType reqOthrSysExgCodeQry
    );

    @WebMethod(operationName = "IdvExgQry", action = "urn:/IdvExgQry")
    @WebResult(name = "RspIdvExgQry", targetNamespace = "http://esb.spdbbiz.com/services/S070030011", partName = "RspIdvExgQry")
    public RspIdvExgQryType idvExgQry(
            @WebParam(partName = "ReqIdvExgQry", name = "ReqIdvExgQry", targetNamespace = "http://esb.spdbbiz.com/services/S070030011")
                    ReqIdvExgQryType reqIdvExgQry
    );
}
