package com.sunyard.core.S070030011;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-01-04T14:13:29.198+08:00
 * Generated source version: 3.2.1
 * 
 */
@WebServiceClient(name = "S070030011", 
                  wsdlLocation = "file:S070030011.wsdl",
                  targetNamespace = "http://esb.spdbbiz.com/services/S070030011/wsdl") 
public class S070030011 extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://esb.spdbbiz.com/services/S070030011/wsdl", "S070030011");
    public final static QName ESBServerSoapEndpoint = new QName("http://esb.spdbbiz.com/services/S070030011/wsdl", "ESBServerSoapEndpoint");
    static {
        URL url = null;
        try {
            url = new URL("file:S070030011.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(S070030011.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:S070030011.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public S070030011(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public S070030011(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public S070030011() {
        super(WSDL_LOCATION, SERVICE);
    }
    




    /**
     *
     * @return
     *     returns ESBServerPortType
     */
    @WebEndpoint(name = "ESBServerSoapEndpoint")
    public ESBServerPortType getESBServerSoapEndpoint() {
        return super.getPort(ESBServerSoapEndpoint, ESBServerPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ESBServerPortType
     */
    @WebEndpoint(name = "ESBServerSoapEndpoint")
    public ESBServerPortType getESBServerSoapEndpoint(WebServiceFeature... features) {
        return super.getPort(ESBServerSoapEndpoint, ESBServerPortType.class, features);
    }

}
