package com.sunyard.core.S040030100;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-01-04T14:13:13.279+08:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://esb.spdbbiz.com/services/S040030100/wsdl", name = "ESBServerPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ESBServerPortType {

    @WebMethod(operationName = "CrdBndngRltnpQry", action = "urn:/CrdBndngRltnpQry")
    @WebResult(name = "RspCrdBndngRltnpQry", targetNamespace = "http://esb.spdbbiz.com/services/S040030100", partName = "RspCrdBndngRltnpQry")
    public RspCrdBndngRltnpQryType crdBndngRltnpQry(
            @WebParam(partName = "ReqCrdBndngRltnpQry", name = "ReqCrdBndngRltnpQry", targetNamespace = "http://esb.spdbbiz.com/services/S040030100")
                    ReqCrdBndngRltnpQryType reqCrdBndngRltnpQry
    );
}
